Repository YAPP-Github/21st-ALL-Rounder-Team-1-Web, pull requests merged in 2022-12, with the labels that each got.

#12 [#7] 공통 컴포넌트(Header, Footer, ScrollFloatBtn) 구현, [#9] 랜딩페이지 구현
  .babelrc.json
  .eslintrc.json
  app/layout.tsx
  app/page.tsx
  components/shared/Footer/index.tsx
  components/shared/Footer/styled.ts
  components/shared/Header/index.tsx
  components/shared/Header/styled.ts
  components/shared/Typography/index.tsx
  components/shared/Typography/styled.ts
  components/shared/index.ts
  components/shared/styled/layout.ts
  next.config.js
  package.json
  public/static/fonts/Pretendard-Bold.woff2
  public/static/fonts/Pretendard-Medium.woff2
  public/static/fonts/Pretendard-Regular.woff2
  public/static/fonts/index.ts
  public/static/icons/add.svg
  public/static/icons/add_photo.svg
  public/static/icons/cancel.svg
  public/static/icons/delete.svg
  public/static/icons/index.ts
  public/static/icons/photo.svg
  public/static/icons/remove.svg
  public/static/icons/search.svg
  public/static/icons/trash.svg
  styles/GlobalStyle.ts
  styles/theme.ts
  yarn.lock
Labels: 💄 UI, 🍱 Support, ⚙️ Enviroment

#13 [#5] 입점신청페이지 버튼 컴포넌트 UI 작업
  .vscode/settings.json
  app/registration/page.tsx
  components/feature/Button/ProductAddBtn/index.tsx
  components/feature/Button/ProductAddBtn/styled.ts
  components/feature/Button/ProductImageBtn/index.tsx
  components/feature/Button/ProductImageBtn/styled.ts
  components/feature/Button/ProductRemoveBtn/index.tsx
  components/feature/Button/ProductRemoveBtn/styled.ts
  components/feature/Button/ScrollTopDownFloatingBtn/index.tsx
  components/feature/Button/ScrollTopDownFloatingBtn/styled.ts
  components/feature/Button/StoreImageBtn/index.tsx
  components/feature/Button/StoreImageBtn/styled.ts
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/styled.ts
  components/feature/index.ts
  components/shared/Button/LargeBtn/index.tsx
  components/shared/Button/LargeBtn/styled.ts
  components/shared/index.ts
  public/static/icons/bottom.svg
  public/static/icons/index.ts
  public/static/icons/top.svg
  styles/style.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: 💄 UI, 🍱 Support

#15 [#8] 공통 컴포넌트(ModalFrame, Snackbar) 구현 2
  .eslintrc.json
  .vscode/settings.json
  app/layout.tsx
  app/page.tsx
  components/feature/Button/ProductImageBtn/index.tsx
  components/feature/Button/StoreImageBtn/index.tsx
  components/feature/Modal/Common/ConfirmModal/index.tsx
  components/feature/Modal/Common/InfoModal/index.tsx
  components/feature/Modal/ExitConfirmModal/index.tsx
  components/feature/Modal/LeaveMemberConfirmModal/index.tsx
  components/feature/Modal/LeaveMemberSuccessModal/index.tsx
  components/feature/Modal/SocialLoginModal/index.tsx
  components/feature/Modal/StoreEditSuccessModal/index.tsx
  components/feature/Modal/StoreProductEditSuccessModal/index.tsx
  components/feature/Modal/StoreProductRequiredWarningModal/index.tsx
  components/feature/Modal/StoreResistrationConfirmModal/index.tsx
  components/feature/Modal/index.ts
  components/feature/Modal/styled.ts
  components/feature/index.ts
  components/shared/ModalFrame/ModalPortal/index.tsx
  components/shared/ModalFrame/index.tsx
  components/shared/ModalFrame/styled.ts
  components/shared/Toast/index.tsx
  components/shared/Toast/styled.ts
  components/shared/Typography/index.tsx
  components/shared/Typography/styled.ts
  components/shared/index.ts
  next.config.js
  package.json
  public/static/icons/index.ts
  public/static/static.d.ts
  styles/GlobalStyle.ts
  styles/style.ts
  styles/styled.d.ts
  styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: 🐛 Bug, 💄 UI, 🍱 Support, ⚙️ Enviroment
