Repository YAPP-Github/21st-ALL-Rounder-Team-1-Web, pull requests merged in 2023-02, with the labels that each got.

#49 [#42] 운영시간 form 구현
  app/registration/step2/page.tsx
  components/feature/Button/DayOffBtn/index.tsx
  components/feature/TimePicker/index.tsx
  core/storeRegistrationService.ts
Labels: ✨ Feature, 💄 UI, ❗️Review

#51 [#43][#47] 소셜 로그인 & 회원가입, 마이페이지 유저 삭제 API 관련 작업
  .eslintrc.json
  app/layout.tsx
  app/mypage/member/page.tsx
  app/oauth/[social]/page.tsx
  app/signin/page.tsx
  app/signup/page.tsx
  components/feature/MyPageSection/MyPageSectionRegisteredStore/index.tsx
  components/feature/MyPageSideBar/index.tsx
  components/shared/Header/index.tsx
  components/shared/Lottie/LoadingCircleLottie/index.tsx
  components/shared/Lottie/LoadingCircleLottie/loading-circle-motion.json
  components/shared/index.ts
  core/apis/axios.ts
  core/apis/constants.ts
  hooks/api/auth/useSignin.ts
  hooks/api/auth/useSignup.ts
  hooks/api/auth/useUserSession.ts
  hooks/useRouteChangeAndRefreshDetect.ts
  package.json
  pages/api/auth/[...nextauth].ts
  store/actions/index.ts
  store/actions/modalStore.ts
  store/actions/oauthStore.ts
  store/actions/userSessionStore.ts
  types/api.ts
  utils/storage.ts
  utils/urlPattern.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI, 🌐 API

#52 [#43] 마이페이지 - 매장정보 조회(GET) & 삭제(DELETE) API 연동 플로우 구현 / 기타 작업
  .eslintrc.json
  app/mypage/store/page.tsx
  app/oauth/[social]/page.tsx
  app/page.tsx
  app/signin/page.tsx
  components/feature/MyPageSection/MyPageSectionEmptyStore/index.tsx
  components/feature/MyPageSection/MyPageSectionRegisteredStore/index.tsx
  components/feature/MyPageSideBar/index.tsx
  components/shared/Lottie/LoadingCircleLottie/loading-circle-motion.json
  components/shared/Motion/MotionShowBox/index.tsx
  components/shared/Motion/index.ts
  core/apis/constants.ts
  hooks/api/store/useDeleteStore.ts
  hooks/api/store/useGetStore.ts
  next.config.js
  package.json
  public/static/images/index.ts
  public/static/images/mypage_store_default.png
  store/actions/oauthStore.ts
  utils/date.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API, 🍱 Support, ⚙️ Enviroment

#54 [#36] step2 매장주소의 위도, 경도 api 붙이기
  app/registration/step2/page.tsx
  components/feature/Button/PostcodePopupOpenBtn/index.tsx
  package.json
  tsconfig.json
  types/env.d.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API, 🙏🏻 Need Modify

#58 [#56] 배포 이전 부수 작업
  components/feature/MyPageSection/MyPageSectionRegisteredStore/index.tsx
Labels: ❗️Review

#62 [#59] 배포 전 부수 작업 - Protected Route 고려
  app/registration/step1/page.tsx
  components/shared/PrivateRoute/index.tsx
  components/shared/index.ts
Labels: ✨ Feature

#60 [#55] 이미지 버튼 오류 해결
  app/registration/step2/page.tsx
  components/feature/Button/StoreImageBtn/index.tsx
  core/s3ImageUploadService.ts
  pages/api/s3-upload.ts
  tsconfig.json
  yarn.lock
Labels: 🚑 Bugfix, ✨ Feature, ❗️Review

#63 [#61] step1 로직 보완 및 api 연결
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  components/feature/Modal/StoreRegistrationExitConfirmModal/index.tsx
  components/feature/ProductInfoElement/index.tsx
  components/feature/TextField/index.tsx
  core/storeRegistrationService.ts
  hooks/api/user/usePatchManager.ts
  package.json
  store/actions/index.ts
  store/actions/productStore.ts
  store/actions/step1Store.ts
  store/actions/step2Store.ts
  types/storeRegistration.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API, 🙏🏻 Need Modify

#68 [#67] DEV 서버 배포 이후 - 버그 핸들링 1
  app/mypage/member/page.tsx
  components/feature/MyPageSection/MyPageSectionLeaveMember/index.tsx
  components/feature/MyPageSideBar/index.tsx
  components/shared/Header/index.tsx
  core/signupService.ts
  hooks/api/auth/useUserSession.ts
Labels: 🐛 Bug, 🚑 Bugfix, ❗️Review

#70 [#69] 404 Not Found 핸들링
  pages/404.tsx
  public/static/images/index.ts
  public/static/images/pump_logo_round.png
  styles/404.module.css
Labels: ✨ Feature, ❗️Review

#75 [#72] 404 페이지 UI 업데이트 & 입점 신청 완료 페이지 UI 구현
  app/registration/layout.tsx
  app/registration/step3/page.tsx
  app/registration/success/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  components/shared/styled/layout.ts
  hooks/api/store/useGetStore.ts
  hooks/api/store/usePatchStore.ts
  pages/404.tsx
  public/static/icons/index.ts
  public/static/images/index.ts
  public/static/images/material-symbols_error-rounded.png
  styles/404.module.css
Labels: ✨ Feature, 💄 UI, ❗️Review

#77 [#76] 빌드 타임 경고 및 디테일 이슈 핸들링
  .vscode/settings.json
  app/layout.tsx
  components/shared/Header/index.tsx
  hooks/api/auth/useUserSession.ts
  package.json
  pageComponents/app/ProtectedRouteWithAuthContainer/index.tsx
  yarn.lock
Labels: 🚑 Bugfix, ✨ Feature, 💄 UI, ❗️Review, ⚙️ Enviroment

#80 [#78] SEO(메타태그, 오픈그래프) 작업 1 & 기타 변경사항 반영
  app/head.tsx
  app/page.tsx
Labels: 🍱 Support

#88 [#87] 기능상의 심각한 오류 해결
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  components/feature/TextField/styled.ts
Labels: 🚑 Bugfix, ✨ Feature, ❗️Review

#92 [#91] QA - 회원가입 페이지
  app/signup/page.tsx
  constants/signup.ts
Labels: 🚑 Bugfix

#94 [#93] 2차 QA 사항 반영
  .vscode/settings.json
  app/registration/step2/page.tsx
Labels: 🚑 Bugfix, ✨ Feature

#96 Release Ver 1.0.1
  app/oauth/[social]/page.tsx
  app/signup/page.tsx
  hooks/api/auth/useUserSession.ts
  pageComponents/app/ProtectedRouteWithAuthContainer/index.tsx
Labels: 🚑 Bugfix
