Repository YAPP-Github/21st-ALL-Rounder-Team-1-Web, pull requests merged in 2023-01, with the labels that each got.

#17 [#14] 입점신청페이지 TextFileds, Selection controls(Radio Button, DropDown) UI 작업
  .vscode/settings.json
  app/mypage/page.tsx
  app/registration/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  components/feature/Button/ProductAddBtn/styled.ts
  components/feature/Button/ProductImageBtn/index.tsx
  components/feature/Button/ProductRemoveBtn/styled.ts
  components/feature/Button/RadioBtn/index.tsx
  components/feature/Button/RadioBtn/styled.ts
  components/feature/Button/ScrollTopDownFloatingBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/styled.ts
  components/feature/DropDownList/index.tsx
  components/feature/DropDownList/styled.ts
  components/feature/TextField/index.tsx
  components/feature/TextField/styled.ts
  components/feature/index.ts
  components/shared/Button/LargeBtn/index.tsx
  package.json
  public/static/icons/bottom.svg
  public/static/icons/index.ts
  public/static/icons/radio_checked.svg
  public/static/icons/top.svg
  styles/style.ts
  styles/styled.d.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI

#20 [#18] 추가 에셋, 랜딩페이지 & Modal 컨텐츠 변경사항 반영
  app/RootStyleRegistry.tsx
  app/login/page.tsx
  app/page.tsx
  components/feature/Button/SocialLoginBtn/index.tsx
  components/feature/Button/SocialLoginBtn/styled.ts
  components/feature/Modal/LeaveMemberConfirmModal/index.tsx
  components/feature/Modal/SocialLoginModal/index.tsx
  components/feature/Modal/StoreEditCompletionConfirmModal/index.tsx
  components/feature/Modal/StoreProductEditExitConfirmModal/index.tsx
  components/feature/Modal/StoreProductRequiredWarningModal/index.tsx
  components/feature/Modal/StoreRegistrationCancelConfirmModal/index.tsx
  components/feature/Modal/StoreRegistrationCancelSuccessModal/index.tsx
  components/feature/Modal/StoreRegistrationConfirmModal/index.tsx
  components/feature/Modal/StoreRegistrationExitConfirmModal/index.tsx
  components/feature/Modal/StoreRegistrationStepChangeConfirmModal/index.tsx
  components/feature/index.ts
  components/shared/Footer/index.tsx
  components/shared/Footer/styled.ts
  components/shared/Header/index.tsx
  components/shared/Typography/index.tsx
  components/shared/Typography/styled.ts
  components/shared/styled/layout.ts
  lib/styled-components.tsx
  public/static/icons/arrow_right.svg
  public/static/icons/index.ts
  public/static/images/index.ts
  public/static/images/kakao_symbol.png
  public/static/images/naver_symbol.png
  styles/GlobalStyle.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: 💄 UI, 🍱 Support

#23 [#16] 입점신청페이지 Tab 구현
  .vscode/settings.json
  app/registration/layout.tsx
  app/registration/page.tsx
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  app/registration/step3/page.tsx
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/styled.ts
  components/feature/Tab/index.tsx
  components/feature/Tab/styled.ts
  components/feature/index.ts
  components/shared/Button/LargeBtn/index.tsx
  components/shared/Button/LargeBtn/styled.ts
Labels: ✨ Feature, 💄 UI

#24 [#19] 입점신청페이지 레이아웃 틀 잡기
  app/registration/layout.tsx
  app/registration/page.tsx
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/RegistrationHeader/index.tsx
  components/feature/RegistrationHeader/styled.ts
  components/feature/Tab/index.tsx
  components/feature/Tab/styled.ts
  components/feature/TextField/index.tsx
  components/feature/index.ts
  components/shared/Button/LargeBtn/index.tsx
  components/shared/styled/layout.ts
  styles/style.ts
  styles/styled.d.ts
Labels: 💄 UI

#26 [#21] 에셋(Color, Images) 업데이트 사항 반영
  app/head.tsx
  app/page.tsx
  app/registration/page.tsx
  components/feature/Button/ProductImageBtn/index.tsx
  components/feature/Modal/Common/InfoModal/index.tsx
  components/shared/Footer/styled.ts
  components/shared/Header/index.tsx
  public/favicon.ico
  public/static/images/index.ts
  public/static/images/pump_logo.png
  styles/style.ts
  styles/styled.d.ts
  styles/theme.ts
Labels: 💄 UI, 🍱 Support

#27 [#22] 주소검색 모달창
  .eslintrc.json
  .vscode/settings.json
  app/registration/page.tsx
  app/registration/step2/page.tsx
  components/feature/Button/PostcodePopupOpenBtn/index.tsx
  components/feature/Button/RadioBtn/index.tsx
  components/feature/Button/ScrollTopDownFloatingBtn/index.tsx
  components/feature/RegistrationHeader/index.tsx
  components/feature/TextField/index.tsx
  components/feature/index.ts
  package.json
  types/domain.ts
  types/index.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API

#31 [#30] 사업자번호 인풋 컴포넌트 구현
  .eslintrc.json
  .gitignore
  app/registration/step2/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  core/storeRegistrationService.ts
Labels: ✨ Feature, 💄 UI, 🌐 API, ⚙️ Enviroment

#35 입점신청페이지 step1,2 UI
  .vscode/settings.json
  app/page.tsx
  app/registration/page.tsx
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  components/feature/Button/PostcodePopupOpenBtn/index.tsx
  components/feature/Button/ProductImageBtn/styled.ts
  components/feature/Button/RadioBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/styled.ts
  components/feature/RegistrationHeader/index.tsx
  components/feature/Tab/index.tsx
  components/feature/TextField/index.tsx
  components/feature/TextField/styled.ts
  components/shared/Button/LargeBtn/index.tsx
  components/shared/styled/layout.ts
  public/static/images/emptyStoreImage.png
  public/static/images/index.ts
  styles/index.ts
  styles/style.ts
  styles/styled.d.ts
Labels: ✨ Feature, 💄 UI

#37 [#34] step1, step2 form onSubmit 로직 구현
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  components/feature/BusinessLicenseTextField/index.tsx
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/Tab/index.tsx
  components/feature/TextField/index.tsx
  components/feature/TextField/styled.ts
  core/storeRegistrationService.ts
  package.json
  store/actions/index.ts
  store/actions/storeRegistrationStore.ts
  store/index.ts
  types/index.ts
  types/storeRegistration.ts
  yarn.lock
Labels: ✨ Feature, 🐎 Performance, 💄 UI

#38 [#10][#28][#29] 회원가입 페이지 구현 & Footer 링크 연결
  app/layout.tsx
  app/mypage/layout.tsx
  app/signin/page.tsx
  app/signup/layout.tsx
  app/signup/page.tsx
  components/feature/Button/ProductImageBtn/styled.ts
  components/feature/SignupTextField/index.tsx
  components/feature/SignupTextField/styled.ts
  components/feature/index.ts
  components/shared/Button/LargeBtn/index.tsx
  components/shared/Checkbox/index.tsx
  components/shared/Checkbox/styled.ts
  components/shared/Footer/index.tsx
  components/shared/Footer/styled.ts
  components/shared/Header/index.tsx
  components/shared/Header/styled.ts
  components/shared/Label/index.tsx
  components/shared/Label/styled.ts
  components/shared/index.ts
  components/shared/styled/layout.ts
  constants/signup.ts
  core/signupService.ts
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/hello.ts
  public/static/icons/checkbox_checked.svg
  public/static/icons/index.ts
  styles/index.ts
  styles/theme.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI, 🌐 API

#40 [#11] 마이페이지 UI 구현
  .eslintrc.json
  app/mypage/layout.tsx
  app/mypage/member/page.tsx
  app/mypage/page.tsx
  app/mypage/store/page.tsx
  app/signin/page.tsx
  components/feature/Button/MyPageActionBtn/index.tsx
  components/feature/Button/MyPageActionBtn/styled.ts
  components/feature/Button/SocialLoginBtn/styled.ts
  components/feature/MyPageSection/MyPageSectionEmptyStore/index.tsx
  components/feature/MyPageSection/MyPageSectionLeaveMember/index.tsx
  components/feature/MyPageSection/MyPageSectionRegisteredStore/index.tsx
  components/feature/MyPageSection/MyPageSectionRegisteredStore/styled.ts
  components/feature/MyPageSection/index.tsx
  components/feature/MyPageSection/styled.ts
  components/feature/MyPageSideBar/index.tsx
  components/feature/MyPageSideBar/styled.ts
  components/feature/index.ts
  components/shared/Header/index.tsx
  components/shared/styled/layout.ts
  next.config.js
  public/static/icons/emblem_kakao.svg
  public/static/icons/emblem_naver.svg
  public/static/icons/index.ts
  public/static/icons/symbol_kakao.svg
  public/static/icons/symbol_naver.svg
  public/static/images/index.ts
  public/static/images/pump_logo.png
Labels: ✨ Feature, 💄 UI

#41 [#33] step2 time picker, 휴무일 지정 버튼 컴포넌트 구현
  app/registration/step2/page.tsx
  components/feature/Button/DayOffBtn/index.tsx
  components/feature/Button/DayOffBtn/styled.ts
  components/feature/Button/StoreResistrationSmallBtn/index.tsx
  components/feature/TimePicker/index.tsx
  components/feature/TimePicker/styled.ts
  components/feature/index.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI, ❗️Review

#44 [#39] 마이페이지 연관 Modal 플로우 연결(without. API 플로우 연동)
  app/mypage/member/page.tsx
  app/mypage/store/page.tsx
  components/feature/Modal/Common/ConfirmModal/index.tsx
  components/feature/Modal/Common/InfoModal/index.tsx
  components/feature/Modal/LeaveMemberConfirmModal/index.tsx
  components/feature/Modal/LeaveMemberSuccessModal/index.tsx
  components/feature/Modal/StoreRegistrationCancelConfirmModal/index.tsx
  components/feature/Modal/StoreRegistrationCancelSuccessModal/index.tsx
  components/feature/MyPageSection/MyPageSectionLeaveMember/index.tsx
  components/feature/MyPageSection/MyPageSectionRegisteredStore/index.tsx
  components/feature/MyPageSection/styled.ts
  components/feature/MyPageSideBar/index.tsx
  components/shared/ModalFrame/index.tsx
  components/shared/ModalFrame/styled.ts
  store/actions/index.ts
  store/actions/modalStore.ts
Labels: ✨ Feature, 💄 UI, ❗️Review

#46 [#45] 랜딩 페이지 버전업
  app/page.tsx
  components/shared/Footer/index.tsx
  components/shared/Footer/styled.ts
  components/shared/Header/styled.ts
  components/shared/Typography/index.tsx
  components/shared/Typography/styled.ts
  components/shared/styled/layout.ts
  package.json
  public/static/icons/index.ts
  public/static/icons/instagram.svg
  public/static/images/index.ts
  public/static/images/landing_advantage.002.png
  public/static/images/landing_advantage_001.png
  public/static/images/landing_app.png
  public/static/images/landing_feature_001.png
  public/static/images/landing_feature_002.png
  public/static/images/landing_feature_003.png
  styles/styled.d.ts
  styles/theme.ts
  yarn.lock
Labels: 💄 UI, ⚙️ Enviroment

#48 [#32] 이미지 버튼(매장사진) 완전 구현
  app/registration/step1/page.tsx
  app/registration/step2/page.tsx
  components/feature/Button/ProductImageBtn/index.tsx
  components/feature/Button/ProductImageBtn/styled.ts
  components/feature/Button/RadioBtn/index.tsx
  components/feature/Button/StoreImageBtn/index.tsx
  components/feature/Button/StoreImageBtn/styled.ts
  components/feature/ShowImageContent/index.tsx
  components/feature/ShowImageContent/styled.ts
  components/feature/TimePicker/styled.ts
  core/s3ImageUploadService.ts
  next.config.js
  package.json
  pages/api/s3-upload.ts
  public/static/icons/cancel.svg
  store/actions/storeRegistrationStore.ts
  tsconfig.json
  types/env.d.ts
  yarn.lock
Labels: 🐛 Bug, ✨ Feature, 💄 UI
